// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4yxRDmJJrdz21esiEvqZKZp2iVowNkOM',
    appId: '1:764339439566:web:7221cfbd3b3be388644d9f',
    messagingSenderId: '764339439566',
    projectId: 'todolist-cb09a',
    authDomain: 'todolist-cb09a.firebaseapp.com',
    storageBucket: 'todolist-cb09a.appspot.com',
    measurementId: 'G-6MQHL56RLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC09ixwp6YDBN0fBcNpSiZol_3U2uBoIPo',
    appId: '1:764339439566:android:21d6433739985a91644d9f',
    messagingSenderId: '764339439566',
    projectId: 'todolist-cb09a',
    storageBucket: 'todolist-cb09a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3iqlaD3lrsSs7-tkf5NAH26tO3qUIaT4',
    appId: '1:764339439566:ios:fefa3ad704699bc1644d9f',
    messagingSenderId: '764339439566',
    projectId: 'todolist-cb09a',
    storageBucket: 'todolist-cb09a.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3iqlaD3lrsSs7-tkf5NAH26tO3qUIaT4',
    appId: '1:764339439566:ios:734866ed4baab424644d9f',
    messagingSenderId: '764339439566',
    projectId: 'todolist-cb09a',
    storageBucket: 'todolist-cb09a.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
